version: '3.6'
services:
  web:
    image: samuelsantosdev/php56_apc:1.5
    networks:
      - frontend
    volumes: 
      - MY_WWW_PATH_HERE:/var/www/localhost
    ports:
      - "80:80"
networks:
  frontend:
    driver: overlay
